### PR TITLE
Allow user to include/exclude categories in a test run

### PR DESCRIPTION
**Pull request by tbrushwyler**
Allow user to include/exclude categories in a test run based on the documentation [here](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-categorized-tests).

### CODE REVIEW

**Comment by godrei** [comment]
Hi @tbrushwyler ,
thanks for your PR!

The `--exclude-category` and `--include-category` is only available for: `Xamarin.UITests` test runs.

Since this input is not available for every Test Framework and in the feature our users may want to use other options as well, we need a more flexible solution.

What we do in this cases is: wire in a new 'wildcard' input (mostly called options/additional_options), which input's value will be assigned to the end of the prepared command (`appcenter test run ...`).

For example in the gradle-runner step: https://github.com/bitrise-io/steps-gradle-runner/blob/master/step.yml#L202

This way other options can be passed as well, without creating input for every possible argumentum (`appcenter test run ... [additional_options]`).

Using this pattern you could specify the include and exclude patterns for this step, like:

```
    - appcenter-test::./:
        inputs:
        - token: $API_TOKEN
        - app: app-center-bot/Multiplatform-Android-1
        - framework: espresso
        - devices: cdf43495
        - series: master
        - locale: en_US
        - app_path: $BITRISE_APK_PATH
        - test_dir: ./app/build/outputs/apk/androidTest/debug
       - options: --include-category 'A|B|C' --exclude-category 'A+B,C'
```

this config would produce a command: `appcenter test run ... --include-category 'A|B|C' --exclude-category 'A+B,C'`

**Review by godrei — CHANGES_REQUESTED** [review]
Please have a look at my comment

**Comment by tbrushwyler** [comment]
@godrei could you please share the error message from Bitrise? I don't have access to see why the check failed.

**Comment by godrei** [comment]
Hi @tbrushwyler ,
sorry for my late response, the update looks great to me.

Th ci build has an internal issue, i'm working on the fix.

**Review by godrei — APPROVED** [review]

**Comment by godrei** [comment]
@tbrushwyler ,
thanks for this update!

**Comment by godrei** [comment]
@tbrushwyler the new version (0.9.1) is available in the steplib, thanks again!

**Pull request merged**
